### ISSUE TITLE
Too much memory occupied when surrogate

### ISSUE THREAD

**Issue by cissieAB** [nathanwbrei/phasm#5]
The pde-example with surrogate seems to occupy much more memory than assumed. Needs double check on that.

See the comment below.  
https://github.com/nathanwbrei/phasm/blob/c1c9488ba77f932b41303cc89eecc4fadd30849b/examples/pde_solver/diffusion_pde_solver.cpp#L12-L15

**Comment by cissieAB** [comment]
Information given in the containerized env @nathanwbrei 
```
=================================================================
==57689==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 176 byte(s) in 1 object(s) allocated from:
    #0 0x7f234f5d51c7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x55f712a130f0 in phasm::Cursor<double>::primitives(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<long, std::allocator<long> >&&, phasm::Direction) (/w/epsci-sciwork18/xmei/phasm/build/install/bin/phasm-example-pdesolver+0x1ab0f0)
    #2 0x55f712a0ad00 in phasm::SurrogateBuilder& phasm::SurrogateBuilder::local_primitive<double>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, phasm::Direction, std::vector<long, std::allocator<long> >&&) (/w/epsci-sciwork18/xmei/phasm/build/install/bin/phasm-example-pdesolver+0x1a2d00)
    #3 0x55f7129f2c0f in __static_initialization_and_destruction_0(int, int) (/w/epsci-sciwork18/xmei/phasm/build/install/bin/phasm-example-pdesolver+0x18ac0f)
    #4 0x55f7129f31da in _GLOBAL__sub_I__Z17make_forcing_termPdi (/w/epsci-sciwork18/xmei/phasm/build/install/bin/phasm-example-pdesolver+0x18b1da)
    #5 0x7f22df5d7eba in call_init ../csu/libc-start.c:145
    #6 0x7f22df5d7eba in __libc_start_main_impl ../csu/libc-start.c:379

Direct leak of 176 byte(s) in 1 object(s) allocated from:
    #0 0x7f234f5d51c7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x55f712a130f0 in phasm::Cursor<double>::primitives(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<long, std::allocator<long> >&&, phasm::Direction) (/w/epsci-sciwork18/xmei/phasm/build/install/bin/phasm-example-pdesolver+0x1ab0f0)
    #2 0x55f712a0ad00 in phasm::SurrogateBuilder& phasm::SurrogateBuilder::local_primitive<double>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, phasm::Direction, std::vector<long, std::allocator<long> >&&) (/w/epsci-sciwork18/xmei/phasm/build/install/bin/phasm-example-pdesolver+0x1a2d00)
    #3 0x55f7129f2b0e in __static_initialization_and_destruction_0(int, int) (/w/epsci-sciwork18/xmei/phasm/build/install/bin/phasm-example-pdesolver+0x18ab0e)
    #4 0x55f7129f31da in _GLOBAL__sub_I__Z17make_forcing_termPdi (/w/epsci-sciwork18/xmei/phasm/build/install/bin/phasm-example-pdesolver+0x18b1da)
    #5 0x7f22df5d7eba in call_init ../csu/libc-start.c:145
    #6 0x7f22df5d7eba in __libc_start_main_impl ../csu/libc-start.c:379

Indirect leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7f234f5d51c7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x55f712a1a6b9 in __gnu_cxx::new_allocator<long>::allocate(unsigned long, void const*) (/w/epsci-sciwork18/xmei/phasm/build/install/bin/phasm-example-pdesolver+0x1b26b9)
    #2 0x55f712a159ef in std::allocator_traits<std::allocator<long> >::allocate(std::allocator<long>&, unsigned long) (/w/epsci-sciwork18/xmei/phasm/build/install/bin/phasm-example-pdesolver+0x1ad9ef)
    #3 0x55f712a1003b in std::_Vector_base<long, std::allocator<long> >::_M_allocate(unsigned long) (/w/epsci-sciwork18/xmei/phasm/build/install/bin/phasm-example-pdesolver+0x1a803b)
    #4 0x55f712a0e958 in void std::vector<long, std::allocator<long> >::_M_range_initialize<long const*>(long const*, long const*, std::forward_iterator_tag) (/w/epsci-sciwork18/xmei/phasm/build/install/bin/phasm-example-pdesolver+0x1a6958)
    #5 0x55f712a05cce in std::vector<long, std::allocator<long> >::vector(std::initializer_list<long>, std::allocator<long> const&) (/w/epsci-sciwork18/xmei/phasm/build/install/bin/phasm-example-pdesolver+0x19dcce)
    #6 0x55f7129f2bc1 in __static_initialization_and_destruction_0(int, int) (/w/epsci-sciwork18/xmei/phasm/build/install/bin/phasm-example-pdesolver+0x18abc1)
    #7 0x55f7129f31da in _GLOBAL__sub_I__Z17make_forcing_termPdi (/w/epsci-sciwork18/xmei/phasm/build/install/bin/phasm-example-pdesolver+0x18b1da)
    #8 0x7f22df5d7eba in call_init ../csu/libc-start.c:145
    #9 0x7f22df5d7eba in __libc_start_main_impl ../csu/libc-start.c:379

Indirect leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7f234f5d51c7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x55f712a1a6b9 in __gnu_cxx::new_allocator<long>::allocate(unsigned long, void const*) (/w/epsci-sciwork18/xmei/phasm/build/install/bin/phasm-example-pdesolver+0x1b26b9)
    #2 0x55f712a159ef in std::allocator_traits<std::allocator<long> >::allocate(std::allocator<long>&, unsigned long) (/w/epsci-sciwork18/xmei/phasm/build/install/bin/phasm-example-pdesolver+0x1ad9ef)
    #3 0x55f712a1003b in std::_Vector_base<long, std::allocator<long> >::_M_allocate(unsigned long) (/w/epsci-sciwork18/xmei/phasm/build/install/bin/phasm-example-pdesolver+0x1a803b)
    #4 0x55f712a0e958 in void std::vector<long, std::allocator<long> >::_M_range_initialize<long const*>(long const*, long const*, std::forward_iterator_tag) (/w/epsci-sciwork18/xmei/phasm/build/install/bin/phasm-example-pdesolver+0x1a6958)
    #5 0x55f712a05cce in std::vector<long, std::allocator<long> >::vector(std::initializer_list<long>, std::allocator<long> const&) (/w/epsci-sciwork18/xmei/phasm/build/install/bin/phasm-example-pdesolver+0x19dcce)
    #6 0x55f7129f2aba in __static_initialization_and_destruction_0(int, int) (/w/epsci-sciwork18/xmei/phasm/build/install/bin/phasm-example-pdesolver+0x18aaba)
    #7 0x55f7129f31da in _GLOBAL__sub_I__Z17make_forcing_termPdi (/w/epsci-sciwork18/xmei/phasm/build/install/bin/phasm-example-pdesolver+0x18b1da)
    #8 0x7f22df5d7eba in call_init ../csu/libc-start.c:145
    #9 0x7f22df5d7eba in __libc_start_main_impl ../csu/libc-start.c:379
```

**Comment by cissieAB** [comment]
## tutorial-example
```
Singularity> ./install/bin/phasm-example-tutorial 
=================================================================
==62070==ERROR: AddressSanitizer: unknown-crash on address 0x7fa5ce69b000 at pc 0x7fa5cdcebf37 bp 0x7ffd1c1b54d0 sp 0x7ffd1c1b4c78
READ of size 8 at 0x7fa5ce69b000 thread T0
    #0 0x7fa5cdcebf36 in __interceptor_memmove ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:810
    #1 0x7fa590fbb7b7 in at::detail::tensor_cpu<double>(c10::ArrayRef<double>, c10::TensorOptions const&)::{lambda()#1}::operator()() const (/deps/libtorch/lib/libtorch_cpu.so+0x13bb7b7)
    #2 0x7fa590fbe4aa in at::Tensor at::detail::tensor_cpu<double>(c10::ArrayRef<double>, c10::TensorOptions const&) (/deps/libtorch/lib/libtorch_cpu.so+0x13be4aa)
    #3 0x7fa590fb9c06 in at::tensor(c10::ArrayRef<double>, c10::TensorOptions const&) (/deps/libtorch/lib/libtorch_cpu.so+0x13b9c06)
    #4 0x5611deae9008 in torch::detail::TensorDataContainer::TensorDataContainer(c10::ArrayRef<double>) (/w/epsci-sciwork18/xmei/phasm/build/install/bin/phasm-example-tutorial+0x24d008)
    #5 0x5611dec3f88b in phasm::tensor::tensor<double>(double*, std::vector<long, std::allocator<long> >) (/w/epsci-sciwork18/xmei/phasm/build/install/bin/phasm-example-tutorial+0x3a388b)
    #6 0x5611dec3a5f4 in phasm::TensorIso<double>::to(double*) (/w/epsci-sciwork18/xmei/phasm/build/install/bin/phasm-example-tutorial+0x39e5f4)
    #7 0x5611dec3a135 in phasm::Optic<double>::unsafe_to(phasm::any_ptr) (/w/epsci-sciwork18/xmei/phasm/build/install/bin/phasm-example-tutorial+0x39e135)
    #8 0x5611dec4dd55 in phasm::ModelVariable::captureTrainingOutput(phasm::any_ptr const&) (/w/epsci-sciwork18/xmei/phasm/build/install/bin/phasm-example-tutorial+0x3b1d55)
    #9 0x5611dec4e948 in phasm::CallSiteVariable::captureAllTrainingOutputs() (/w/epsci-sciwork18/xmei/phasm/build/install/bin/phasm-example-tutorial+0x3b2948)
    #10 0x5611dec4bf72 in phasm::Surrogate::call_original_and_capture() (/w/epsci-sciwork18/xmei/phasm/build/install/bin/phasm-example-tutorial+0x3aff72)
    #11 0x5611deab8bad in C_A_T_C_H_T_E_S_T_2() (/w/epsci-sciwork18/xmei/phasm/build/install/bin/phasm-example-tutorial+0x21cbad)
    #12 0x5611dea89cc2 in Catch::TestInvokerAsFunction::invoke() const (/w/epsci-sciwork18/xmei/phasm/build/install/bin/phasm-example-tutorial+0x1edcc2)
    #13 0x5611dea879ad in Catch::TestCase::invoke() const (/w/epsci-sciwork18/xmei/phasm/build/install/bin/phasm-example-tutorial+0x1eb9ad)
    #14 0x5611dea79d73 in Catch::RunContext::invokeActiveTestCase() (/w/epsci-sciwork18/xmei/phasm/build/install/bin/phasm-example-tutorial+0x1ddd73)
    #15 0x5611dea79577 in Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (/w/epsci-sciwork18/xmei/phasm/build/install/bin/phasm-example-tutorial+0x1dd577)
    #16 0x5611dea75cf8 in Catch::RunContext::runTest(Catch::TestCase const&) (/w/epsci-sciwork18/xmei/phasm/build/install/bin/phasm-example-tutorial+0x1d9cf8)
    #17 0x5611dea7e083 in Catch::(anonymous namespace)::TestGroup::execute() (/w/epsci-sciwork18/xmei/phasm/build/install/bin/phasm-example-tutorial+0x1e2083)
    #18 0x5611dea80d37 in Catch::Session::runInternal() (/w/epsci-sciwork18/xmei/phasm/build/install/bin/phasm-example-tutorial+0x1e4d37)
    #19 0x5611dea80634 in Catch::Session::run() (/w/epsci-sciwork18/xmei/phasm/build/install/bin/phasm-example-tutorial+0x1e4634)
    #20 0x5611deb33b85 in int Catch::Session::run<char>(int, char const* const*) (/w/epsci-sciwork18/xmei/phasm/build/install/bin/phasm-example-tutorial+0x297b85)
    #21 0x5611deab8558 in main (/w/epsci-sciwork18/xmei/phasm/build/install/bin/phasm-example-tutorial+0x21c558)
    #22 0x7fa55ddd7d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #23 0x7fa55ddd7e3f in __libc_start_main_impl ../csu/libc-start.c:392
    #24 0x5611dea4d9b4 in _start (/w/epsci-sciwork18/xmei/phasm/build/install/bin/phasm-example-tutorial+0x1b19b4)

Address 0x7fa5ce69b000 is a wild pointer.
SUMMARY: AddressSanitizer: unknown-crash ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:810 in __interceptor_memmove
Shadow bytes around the buggy address:
  0x0ff539ccb5b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff539ccb5c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff539ccb5d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff539ccb5e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff539ccb5f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0ff539ccb600:[fe]fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe
  0x0ff539ccb610: fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe
  0x0ff539ccb620: fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe
  0x0ff539ccb630: fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe
  0x0ff539ccb640: fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe
  0x0ff539ccb650: fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==62070==ABORTING

```

**Comment by cissieAB** [comment]
See this post for other test results with CUDA

https://github.com/nathanwbrei/phasm/pull/12#issuecomment-1358652951
